var JadwalWidget=(function(e){Object.defineProperty(e,Symbol.toStringTag,{value:`Module`});var t=`jadwal-widget`,n=`jadwal:height:1`,r=320,i=2e4,a=2,o=new Set([`fr`,`de`,`it`,`ar`]),s=new Set([`semaine`,`cours`,`mois`]),c=new Set([`kids`,`youth`,`women`,`adults`,`open`]),l={fr:{titre:`Programme des cours`,lien:`Voir le programme complet`,mention:`Proposé gratuitement par jadwal, un service de Voltia`},de:{titre:`Kursprogramm`,lien:`Das ganze Programm ansehen`,mention:`Kostenlos bereitgestellt von jadwal, einem Dienst von Voltia`},it:{titre:`Programma dei corsi`,lien:`Vedi tutto il programma`,mention:`Offerto gratuitamente da jadwal, un servizio di Voltia`},ar:{titre:`برنامج الدروس`,lien:`عرض البرنامج كاملًا`,mention:`مقدَّم مجانًا من jadwal، خدمة من Voltia`}},u=(()=>{try{let e=document.currentScript;return new URL(e?.src??``,document.baseURI).origin}catch{return``}})(),d=`
:host { display: block; contain: content; }
iframe { display: block; width: 100%; border: 0; color-scheme: normal; }
footer {
	font: 400 0.8rem/1.5 system-ui, -apple-system, sans-serif;
	color: #555;
	padding: 0.4rem 0 0;
	display: flex;
	flex-wrap: wrap;
	gap: 0.5rem;
}
a { color: #0f5c55; min-height: 24px; }
`,f=class extends HTMLElement{static observedAttributes=[`org`,`lang`,`view`,`audience`,`min-height`,`base`];#e;#t;#n;#r;#i=0;#a=e=>this.#f(e);connectedCallback(){this.#e||this.#o(),window.addEventListener(`message`,this.#a),this.#d()}disconnectedCallback(){window.removeEventListener(`message`,this.#a)}attributeChangedCallback(){this.#e&&this.#d()}#o(){let e=this.attachShadow({mode:`open`});this.#e=e;let t=document.createElement(`style`);t.textContent=d;let n=document.createElement(`footer`);this.#n=document.createElement(`a`),this.#n.target=`_blank`,this.#n.rel=`noopener`,this.#r=document.createElement(`span`),n.append(this.#n,this.#r),e.append(t,n)}#s(){let e=this.getAttribute(`lang`)?.trim().toLowerCase();return e&&o.has(e)?e:void 0}#c(){let e=Number(this.getAttribute(`min-height`));return!Number.isFinite(e)||e<=0?r:Math.min(Math.round(e),i)}#l(){let e=this.getAttribute(`base`)?.trim();if(e)try{return new URL(e,document.baseURI).origin}catch{}return u||window.location.origin}#u(e){let t=this.getAttribute(`org`)?.trim();if(!t)return;let n=this.#s(),r;try{r=new URL(`/m/${encodeURIComponent(t)}${n?`/${n}`:``}`,`${this.#l()}/`)}catch{return}let i=this.getAttribute(`view`)?.trim();i&&s.has(i)&&i!==`semaine`&&r.searchParams.set(`vue`,i);let a=this.getAttribute(`audience`)?.trim();return a&&c.has(a)&&r.searchParams.set(`public`,a),e&&r.searchParams.set(`embed`,`1`),r.toString()}#d(){let e=this.#e,t=this.#n,n=this.#r;if(!e||!t||!n)return;let r=l[this.#s()??`fr`]??l.fr;t.textContent=r.lien,n.textContent=r.mention;let i=this.#u(!1),a=this.#u(!0);if(!i||!a){this.#t?.remove(),this.#t=void 0,t.removeAttribute(`href`);return}t.href=i,this.#t?.remove();let o=document.createElement(`iframe`);o.title=r.titre,o.referrerPolicy=`no-referrer`,this.#i=this.#c(),o.style.height=`${this.#i}px`,o.src=a,this.#t=o,e.insertBefore(o,e.querySelector(`footer`))}#f(e){let t=this.#t;if(!t?.contentWindow||e.source!==t.contentWindow)return;let r;try{r=new URL(t.src).origin}catch{return}if(e.origin!==r)return;let o=e.data;if(!o||typeof o!=`object`||o.type!==n)return;let s=o.height;if(typeof s!=`number`||!Number.isFinite(s))return;let c=Math.min(Math.max(Math.round(s),this.#c()),i);Math.abs(c-this.#i)<=a||(this.#i=c,t.style.height=`${c}px`)}};function p(){typeof customElements>`u`||customElements.get(`jadwal-widget`)||customElements.define(t,f)}return p(),e.JadwalWidget=f,e.TAG_NAME=t,e.register=p,e})({});