ALTER POLICY "audit_log_insert" ON "audit_log" TO jadwal_app WITH CHECK ("audit_log"."organization_id" = (select jadwal.current_org_id())
				and ("audit_log"."actor_id" is null or exists (select 1 from "user" u where u."id" = "audit_log"."actor_id")));--> statement-breakpoint
ALTER POLICY "course_insert" ON "course" TO jadwal_app WITH CHECK ("course"."organization_id" = (select jadwal.current_org_id()) and ("course"."updated_by" is null or exists (select 1 from "user" u where u."id" = "course"."updated_by")));--> statement-breakpoint
ALTER POLICY "course_update" ON "course" TO jadwal_app USING ("course"."organization_id" = (select jadwal.current_org_id())) WITH CHECK ("course"."organization_id" = (select jadwal.current_org_id()) and ("course"."updated_by" is null or exists (select 1 from "user" u where u."id" = "course"."updated_by")));--> statement-breakpoint
ALTER POLICY "membership_insert" ON "membership" TO jadwal_app WITH CHECK ("membership"."organization_id" = (select jadwal.current_org_id()) and ("membership"."user_id" is null or exists (select 1 from "user" u where u."id" = "membership"."user_id")));--> statement-breakpoint
ALTER POLICY "membership_update" ON "membership" TO jadwal_app USING ("membership"."organization_id" = (select jadwal.current_org_id())) WITH CHECK ("membership"."organization_id" = (select jadwal.current_org_id()) and ("membership"."user_id" is null or exists (select 1 from "user" u where u."id" = "membership"."user_id")));--> statement-breakpoint
ALTER POLICY "pause_insert" ON "pause" TO jadwal_app WITH CHECK ("pause"."organization_id" = (select jadwal.current_org_id()) and ("pause"."created_by" is null or exists (select 1 from "user" u where u."id" = "pause"."created_by")));--> statement-breakpoint
ALTER POLICY "pause_update" ON "pause" TO jadwal_app USING ("pause"."organization_id" = (select jadwal.current_org_id())) WITH CHECK ("pause"."organization_id" = (select jadwal.current_org_id()) and ("pause"."created_by" is null or exists (select 1 from "user" u where u."id" = "pause"."created_by")));--> statement-breakpoint
ALTER POLICY "session_exception_insert" ON "session_exception" TO jadwal_app WITH CHECK ("session_exception"."organization_id" = (select jadwal.current_org_id()) and ("session_exception"."created_by" is null or exists (select 1 from "user" u where u."id" = "session_exception"."created_by")));--> statement-breakpoint
ALTER POLICY "session_exception_update" ON "session_exception" TO jadwal_app USING ("session_exception"."organization_id" = (select jadwal.current_org_id())) WITH CHECK ("session_exception"."organization_id" = (select jadwal.current_org_id()) and ("session_exception"."created_by" is null or exists (select 1 from "user" u where u."id" = "session_exception"."created_by")));